[versions]
baksmali = "3.0.9.RE"
commons_io = "2.21.0"
commons_cli = "1.11.0"
commons_lang3 = "3.20.0"
commons_text = "1.15.0"
guava = "33.5.0-jre"
junit = "4.13.2"
proguard = "7.9.0"
smali = "3.0.9.RE"
xmlpull = "1.1.4c"
xmlunit = "2.11.0"
shadow = "9.3.2" # <--- ACTUALIZADO: versión recomendada para Gradle 9

[libraries]
baksmali = { module = "com.extenre:smali-baksmali", version.ref = "baksmali" }
commons_cli = { module = "commons-cli:commons-cli", version.ref = "commons_cli"}
commons_io = { module = "commons-io:commons-io",    version.ref = "commons_io" }
commons_lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons_lang3" }
commons_text = { module = "org.apache.commons:commons-text", version.ref = "commons_text" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { module = "junit:junit", version.ref = "junit" }
proguard = { module = "com.guardsquare:proguard-gradle", version.ref = "proguard" }
smali = { module = "com.extenre:smali", version.ref = "smali" }
xmlpull = { module = "xpp3:xpp3", version.ref = "xmlpull" }
xmlunit = { module = "org.xmlunit:xmlunit-legacy", version.ref = "xmlunit" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" } # <--- NUEVO ID y versión
